default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ali_amrah
  password: click227
  host: localhost

development:
  <<: *default
  database: DEMO_DEPLOY_db_dev


test:
  <<: *default
  database: DEMO_DEPLOY_db_test

production:
  <<: *default
  database: DEMO_DEPLOY_db_production
  username: DEMO_DEPLOY
  password: <%= ENV['DEMO_DEPLOY_DATABASE_PASSWORD'] %>